[global]
pid = /home/ayanami/myfile/learn/Arise/Arise/deploy/php-fpm.pid
error_log = /home/ayanami/myfile/learn/Arise/Arise/deploy/php-fpm.log
daemonize = no

[www]
listen = /home/ayanami/myfile/learn/Arise/Arise/deploy/php-fpm.sock
listen.owner = ayanami
listen.group = ayanami
listen.mode = 0660
user = ayanami
group = ayanami
pm = dynamic
pm.max_children = 20
pm.start_servers = 4
pm.min_spare_servers = 4
pm.max_spare_servers = 12
pm.max_requests = 0
clear_env = no
catch_workers_output = yes
